---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 1024
      cpus: 1
lint:
  name: yamllint
  options:
    config-file: molecule/resources/yaml-lint.yml
platforms:
  - name: ${KVM_NAME:-centos7}
    box: ${KVM_DISTRO:-centos/7}
    groups:
      - rhel
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  log: true
  playbooks:
    vagrant:
      prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
scenario:
  name: kvm  # optional
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - lint
    - dependency
    # - cleanup
    # - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    # - cleanup
    # - destroy
ansible:
  raw_env_vars:
    ANSIBLE_CALLBACK_PLUGINS: ${ANSIBLE_CALLBACK_PLUGINS}
verifier:
  name: goss
  directory: ../resources/tests
  lint:
    name: yamllint
